### ISSUE TITLE
Release Versioning and Upgrade Testing

### ISSUE THREAD

**Issue by ematpl** [cloudfoundry-incubator/diego-dev-notes#29]
I've just added https://github.com/cloudfoundry-incubator/diego-dev-notes/blob/master/proposals/release-versioning-testing.md as an initial proposal for how we'll test upgrades of CF+Diego in CI, and what we intend to signify with release versions in general. Comments and feedback welcome!

**Comment by luan** [comment]
> During the upgrade of the CF deployment to V2, the gorouter and HAproxy will likely be offline for some amount of time, so the Dora instance is not expected to be routable externally then.

We could just deploy 3 nodes of router and HA proxy so that:

> During the upgrade of *\<component\>* to V2, we verify that the Dora instance is always routable.

Can be generalized as a background test that checks that Dora is absolutely **ALWAYS** routable.

> If we introduce changes in the RunInfo that cannot be represented appropriately in the V1 BBS API, do we expect that V1 cells will be able to run that work? If not, is there any way we can ensure that older, incompatible cells won't be assigned work they can't do?

I don't think we can expect it to work, but isn't that then a major version bump? At which point clients using `V1` should still successfully be able to use the system, while clients of `V2` will only be able to do so after there's at least one cell with capacity and upgraded to run their work. That said, we would most likely need to put some placement constraint based on which version the cell support.

**Comment by ematpl** [comment]
- We can HA the router with even 2 nodes, but not HAproxy itself, right?

- Yeah, I was thinking that it would be more appropriate to detect the run-info incompatibility in the auction somehow. In any case, I don't think we could run the new work until `V2` cells come online, but the failure messaging might be better.

**Comment by luan** [comment]
LOL, yeah, nvm.

**Comment by ematpl** [comment]
Closing, as we have implemented this.
